#!/bin/bash
VM_FETCHER_INFO=$1
FETCHER_KEYS_DIR=/tmp
FETCHER_PUBLIC_KEY=$(cat "$FETCHER_KEYS_DIR"/fetcher-key.pub)

sed -i "/FETCHER_PUBLIC_KEY/d" $VM_FETCHER_INFO
echo "FETCHER_PUBLIC_KEY=$FETCHER_PUBLIC_KEY" >> $VM_FETCHER_INFO

