#!/bin/bash
#
# Deploy the scheduler component

#FIXME add classpath and class names to constants

if [[ $# -ne 2 ]]; then
  echo "Usage:" $0 "path/to/private_key storage_size"
  exit 1
fi

PRIVATE_KEY_FILE=$1
STORAGE_SIZE=$2

if [[ ! -f "${PRIVATE_KEY_FILE}" ]]; then
  echo $PRIVATE_KEY_FILE "is not a regular file or does not exist"
  exit 1
fi

if [[ ! "${STORAGE_SIZE}" =~ ^[0-9]+$ ]]; then
  echo "Invalid storage_size" $STORAGE_SIZE
  exit 1
fi

#FIXME not sure if we should keep these declarations here or to load from a config file
#GLOBAL CONSTANTS
REMOTE_BASE_DIR=/tmp
SANDBOX_DIR=/local/esdras/git/sebal-engine
VOMS_CERT_FOLDER=/tmp
KEYSTONE_CERT_FOLDER=/tmp
LDAP_KEYS_FOLDER=/tmp
VOMS_CERT_FILE=x509up_u1210
KEYSTONE_CERT_FILE=keystone_cert
LDAP_PRIVATE_KEY=private_key.pem
LDAP_PUBLIC_KEY=public_key.pem
LOCAL_REPOSITORY_PATH=/local/esdras
REMOTE_REPOSITORY_PATH=/home/fogbow
REMOTE_VOMS_CERT_FOLDER=/home/fogbow/Dev/keys/cert
REMOTE_KEYSTONE_CERT_FOLDER=/home/fogbow/Dev/keys/cert
REMOTE_LDAP_KEYS_FOLDER=/tmp
CONFIG_FILE=$SANDBOX_DIR/config/sebal.conf
CATALOG_CONFIG_FILE=$SANDBOX_DIR/config/catalog.config
SPEC_FILE=$SANDBOX_DIR/config/schedulerSpec
CRAWLER_EXEC_INFO_FILE=$SANDBOX_DIR/crawler/crawler-info/crawler-exec.info
BLOWOUT_PKG_FILE=blowout-pkg.tar.gz
SEBAL_ENGINE_PKG_FILE=sebal-engine-pkg.tar.gz
MANAGER_PKG_FILE=manager-pkg.tar.gz

LOG4J=$SANDBOX_DIR/config/log4j.properties
if [ -f $LOG4J ]; then
CONF_LOG=-Dlog4j.configuration=file:$LOG4J
else
CONF_LOG=
fi

#Execution INFO
SCHEDULER_EXECUTION_INFO=$SANDBOX_DIR/scheduler/scheduler-info/scheduler-exec.info
if [ -f "$SCHEDULER_EXECUTION_INFO" ]; then 
	sudo rm $SCHEDULER_EXECUTION_INFO
fi

if [ ! -e "$SCHEDULER_EXECUTION_INFO" ]; then
	echo "Creating execution info file"
	touch $SCHEDULER_EXECUTION_INFO
	echo "SCHEDULER_INSTANCE_ID=" >> $SCHEDULER_EXECUTION_INFO
	echo "SCHEDULER_USER_NAME=" >> $SCHEDULER_EXECUTION_INFO
	echo "SCHEDULER_INSTANCE_IP=" >> $SCHEDULER_EXECUTION_INFO
	echo "SCHEDULER_INSTANCE_PORT=" >> $SCHEDULER_EXECUTION_INFO
	echo "SCHEDULER_EXTRA_PORT=" >> $SCHEDULER_EXECUTION_INFO
	echo "DB_STORAGE_ID=" >> $SCHEDULER_EXECUTION_INFO
	echo "DB_STORAGE_ATTACHMENT_ID=" >> $SCHEDULER_EXECUTION_INFO
	echo "DB_STORAGE_PORT=" >> $SCHEDULER_EXECUTION_INFO
	echo "DB_STORAGE_FORMATED=NO" >> $SCHEDULER_EXECUTION_INFO
	echo "DB_STORAGE_CREATED=NO" >> $SCHEDULER_EXECUTION_INFO
	echo "SCHEDULER_BASE_DIR=" >> $SCHEDULER_EXECUTION_INFO
	echo "SCHEDULER_RESTLET_PORT=" >> $SCHEDULER_EXECUTION_INFO
fi
sed -i "/START_INFRASTRUCTURE_DATE=/ s/=.*/=$(date)/" $SCHEDULER_EXECUTION_INFO

source $SCHEDULER_EXECUTION_INFO

#FIXME add some doc. i did not understand the purpose of below code
STORAGE_COMMAND="FORMAT";
DATABASE_COMMAND="CREATE";

if [ "$DB_STORAGE_FORMATED" = "YES" ]; then
	STORAGE_COMMAND="RETRIEVE";
fi
if [ "$DB_STORAGE_CREATED" = "YES" ]; then
	DATABASE_COMMAND="LOAD";
fi

########### SCHEDULER INFRASTRUCTURE ##############

# It starts scheduler VM
# Globals
#   CONFIG_FILE
#   SPEC_FILE
# Returns
#   infrastructure description
function create_scheduler_vm() {
  VM_SCHEDULER_INFO=`java $CONF_LOG -cp $SANDBOX_DIR/target/sebal-scheduler-0.0.1-SNAPSHOT.jar:target/lib/* org.fogbowcloud.sebal.engine.infrastructure.InfrastructureMain compute $CONFIG_FILE $SPEC_FILE "false" 2>&1`

  if [[ ! $VM_SCHEDULER_INFO == *"INSTANCE_ID"* ]]; then
    echo $VM_SCHEDULER_INFO
    echo "There is no resource available for deploy Scheduler App." >&2
    exit 1
  fi

  echo $VM_SCHEDULER_INFO
}

#FIXME improve function. we need return values
# It Verifies if storage info exists.
# Globals
#   DB_STORAGE_ID
#   CONFIG_FILE
#   SPEC_FILE
# Args
#  DB_STORAGE_ID
function storage_exists() {
  if [ -n "$DB_STORAGE_ID" ]; then
    STORAGE_STATUS=`java $CONF_LOG -cp $SANDBOX_DIR/target/sebal-scheduler-0.0.1-SNAPSHOT.jar:target/lib/* org.fogbowcloud.sebal.engine.infrastructure.InfrastructureMain "test-storage" $DB_STORAGE_ID $CONFIG_FILE "false" 2>&1`
    STORAGE_STATUS=$(echo $STORAGE_STATUS | cut -d";" -f1 | cut -d"=" -f2)
    echo "Storage status: $STORAGE_STATUS";
    if [ ! $STORAGE_STATUS = "active" ]; then
      DB_STORAGE_ID="";
    fi
  fi
}

# It creates a volume
# Globals
# Args
# Returns
function create_volume() {
  #FIXME check args
  STORAGE_COMMAND="FORMAT";
  sed -i "/DB_STORAGE_FORMATED=/ s/=.*/=NO/" $SCHEDULER_EXECUTION_INFO

  #This tow variables indicates if a new storage is been used. For new storage, the disk must be formated and the database must be created.
  create_vol_args="storage $STORAGE_SIZE $CONFIG_FILE $SPEC_FILE"
  STORAGE_INFO=`java $CONF_LOG -cp $SANDBOX_DIR/target/sebal-scheduler-0.0.1-SNAPSHOT.jar:target/lib/* org.fogbowcloud.sebal.engine.infrastructure.InfrastructureMain storage $STORAGE_SIZE $CONFIG_FILE $SPEC_FILE "false" 2>&1`
  echo $STORAGE_INFO

  DB_STORAGE_ID=$(echo $STORAGE_INFO | cut -d";" -f1 | cut -d"=" -f2)

  echo "New storage created: "$DB_STORAGE_ID
}

# it attaches the volume to the VM
# Globals
# Args
# Returns
function attach_volume() {
#FIXME check vars
#FIXME add proper return
  echo "Attaching $DB_STORAGE_ID to $INSTANCE_ID"
  DB_STORAGE_ATTACHMENT_INFO=`java $CONF_LOG -cp $SANDBOX_DIR/target/sebal-scheduler-0.0.1-SNAPSHOT.jar:target/lib/* org.fogbowcloud.sebal.engine.infrastructure.InfrastructureMain attachment $INSTANCE_ID $DB_STORAGE_ID $CONFIG_FILE $SPEC_FILE "false" 2>&1`

  if [[ ! $DB_STORAGE_ATTACHMENT_INFO == *"ATTACHMENT_ID"* ]]; then
    echo $DB_STORAGE_ATTACHMENT_INFO
    echo "Error while attaching $DB_STORAGE_ID to $INSTANCE_ID."
    exit
  fi

  echo $DB_STORAGE_ATTACHMENT_INFO;
  DB_STORAGE_ATTACHMENT_ID=$(echo $DB_STORAGE_ATTACHMENT_INFO | cut -d";" -f1 | cut -d"=" -f2)
  echo "Attach ID: $DB_STORAGE_ATTACHMENT_ID"
  #Update Storage INFO FILE with the new attachment id.
  sed -i "/DB_STORAGE_ATTACHMENT_ID=/ s/=.*/=$DB_STORAGE_ATTACHMENT_ID/" $SCHEDULER_EXECUTION_INFO
}

#FIXME extract to a method
#Coping scripts to mount disk.
SCRIPTS_DIR="sebal_scripts"
LOCAL_FILE_PATH="$SANDBOX_DIR/scripts/infrastructure/$SCRIPTS_DIR"
REMOTE_FILE_PATH="$REMOTE_BASE_DIR";

#SSH to scheduler VM
# Globals
#   INSTANCE_PORT
#   PRIVATE_KEY_FILE
#   USER_NAME
#   INSTANCE_IP
# Args
#   remote_command
# Returns
function ssh_to_scheduler() {
  #FIXME check remote_command?
  local remote_command=$*
  ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p $INSTANCE_PORT -i $PRIVATE_KEY_FILE  $USER_NAME@$INSTANCE_IP ${remote_command}
}

# Globals
#   INSTANCE_PORT
#   PRIVATE_KEY_FILE
#   USER_NAME
#   INSTANCE_IP
# Args
#   src_path
#   dst_path
# Returns
function scp_to_scheduler() {
  #FIXME how about the -r modified?
  local src_path=$1
  local dst_path=$2
  scp -r -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -P $INSTANCE_PORT -i $PRIVATE_KEY_FILE $src_path $USER_NAME@$INSTANCE_IP:/$dst_path
}

# Globals
#   EXTRA_PORT
# Args
# Returns
#  postgres_port
function parse_postgres_port() {
  IFS=',' read -r -a extraPortsArray <<< $EXTRA_PORT
  arrayLength=${#extraPortsArray[@]};
  for (( i=0; i<${arrayLength}; i++ ));
  do
    actualPort=${extraPortsArray[$i]};
    if [[ $actualPort == *"postgres"* ]]; then
      postgres_port=`echo $actualPort | cut -d":" -f3 | tr -d "}"`
      echo $postgres_port
    fi
  done
}

function parse_restlet_port() {
  IFS=',' read -r -a extraPortsArray <<< $EXTRA_PORT
  arrayLength=${#extraPortsArray[@]};
  for (( i=0; i<${arrayLength}; i++ ));
  do
    actualPort=${extraPortsArray[$i]};
    if [[ $actualPort == *"restlet"* ]]; then
      restlet_port=`echo $actualPort | cut -d":" -f3 | tr -d "}"`
      echo $restlet_port
    fi
  done
}

function execute_scheduler_app() {
  NFS_INSTANCE_IP=$(sed -n 3p $CRAWLER_EXEC_INFO_FILE | cut -d"=" -f2)
  NFS_PORT=$(sed -n 10p $CRAWLER_EXEC_INFO_FILE | cut -d"=" -f2)

  schedulerapp_cmd="sudo sh $SANDBOX_DIR/scripts/cli/scheduler $INSTANCE_IP $DB_STORAGE_PORT $NFS_INSTANCE_IP $NFS_PORT"
  ssh_to_scheduler ${schedulerapp_cmd}
}

function execute_restlet_app() {
  local scheduler_instance_ip=$1
  local restlet_port=$2
  
  restletapp_cmd="sudo sh $SANDBOX_DIR/scripts/infrastructure/$SCRIPTS_DIR/start_restlet_application.sh $scheduler_instance_ip $restlet_port"
  ssh_to_scheduler ${restletapp_cmd}
}

function main() {
  echo "Creating Scheduler VM"
  VM_SCHEDULER_INFO=`create_scheduler_vm`

  #PREPARING VARIABLES FOR SSH/SCP
  #Sample return USER_NAME=fogbow;SSH_HOST=192.168.0.1;SSH_HOST=9000;SSH_HOST=
  INSTANCE_ID=$(echo $VM_SCHEDULER_INFO | cut -d";" -f1 | cut -d"=" -f2)
  USER_NAME=$(echo $VM_SCHEDULER_INFO | cut -d";" -f2 | cut -d"=" -f2)
  INSTANCE_IP=$(echo $VM_SCHEDULER_INFO | cut -d";" -f3 | cut -d"=" -f2)
  INSTANCE_PORT=$(echo $VM_SCHEDULER_INFO | cut -d";" -f4 | cut -d"=" -f2)
  EXTRA_PORT=$(echo $VM_SCHEDULER_INFO | cut -d";" -f5 | cut -d"=" -f2)
  DB_STORAGE_PORT=`parse_postgres_port`
  RESTLET_PORT=`parse_restlet_port`

  #Putting DB info into catalog.config
  sed -i "/DB_ADDRESS/d" $CATALOG_CONFIG_FILE
  sed -i "/DB_PORT/d" $CATALOG_CONFIG_FILE
  echo "DB_ADDRESS=$INSTANCE_IP" >> $CATALOG_CONFIG_FILE
  echo "DB_PORT=$DB_STORAGE_PORT" >> $CATALOG_CONFIG_FILE

  #Putting DB info into sebal.conf
  sed -i "/datastore_ip/d" $CONFIG_FILE
  sed -i "/datastore_port/d" $CONFIG_FILE
  echo "datastore_ip=$INSTANCE_IP" >> $CONFIG_FILE
  echo "datastore_port=$DB_STORAGE_PORT" >> $CONFIG_FILE

  #Updating accounting datastore info in sebal.conf
  sed -i "/accounting_datastore_url/d" $CONFIG_FILE
  sed -i "/local.output/d" $CONFIG_FILE
  echo "accounting_datastore_url=jdbc:h2:/home/fogbow/Dev/sebalScheduleEnv/h2db/orders" >> $CONFIG_FILE
  echo "local.output=/home/fogbow/Dev/sebalScheduleEnv/result" >> $CONFIG_FILE

  echo "Checking if storage exists"
  storage_exists

  echo "Creating volume"
  create_volume

  echo "Attaching volume"
  attach_volume

  echo "Uploading scripts"
  scp_to_scheduler $LOCAL_FILE_PATH $REMOTE_FILE_PATH

  echo "Change script dir permission"
  chmod_cmd="sudo chmod -R 777 $REMOTE_FILE_PATH/$SCRIPTS_DIR"
  ssh_to_scheduler ${chmod_cmd}

  echo "Changing VM timezone"
  timezone_cmd="sudo sh $REMOTE_FILE_PATH/$SCRIPTS_DIR/change_timezone.sh"
  ssh_to_scheduler ${timezone_cmd}

  echo "Mounting volume"
  mount_cmd="sudo sh $REMOTE_FILE_PATH/$SCRIPTS_DIR/mount_partition.sh $STORAGE_COMMAND"
  ssh_to_scheduler ${mount_cmd}
  sed -i "/DB_STORAGE_FORMATED=/ s/=.*/=YES/" $SCHEDULER_EXECUTION_INFO

  echo "Preparing database"
  prepdb_cmd="sudo sh $REMOTE_FILE_PATH/$SCRIPTS_DIR/install_postgres.sh $DATABASE_COMMAND"
  ssh_to_scheduler ${prepdb_cmd}

  echo "Changing database permissions"
  perm_cmd="sudo sh $REMOTE_FILE_PATH/$SCRIPTS_DIR/md5_postgres.sh"
  ssh_to_scheduler ${perm_cmd}

  echo "Installing USGS API in Scheduler VM"
  usgs_install_cmd="sudo sh $REMOTE_FILE_PATH/$SCRIPTS_DIR/install_usgs_api.sh"
  ssh_to_scheduler ${usgs_install_cmd}
  
  echo "Upload scheduler packages"
  sudo sh $SANDBOX_DIR/scripts/infrastructure/$SCRIPTS_DIR/pack_blowout_repository.sh $LOCAL_REPOSITORY_PATH 
  sudo sh $SANDBOX_DIR/scripts/infrastructure/$SCRIPTS_DIR/pack_sebal_engine_repository.sh $LOCAL_REPOSITORY_PATH $SANDBOX_DIR
  sudo sh $SANDBOX_DIR/scripts/infrastructure/$SCRIPTS_DIR/pack_manager_repository.sh $LOCAL_REPOSITORY_PATH
  scp_to_scheduler $LOCAL_REPOSITORY_PATH/$BLOWOUT_PKG_FILE $REMOTE_REPOSITORY_PATH
  scp_to_scheduler $LOCAL_REPOSITORY_PATH/$SEBAL_ENGINE_PKG_FILE $REMOTE_REPOSITORY_PATH
  scp_to_scheduler $LOCAL_REPOSITORY_PATH/$MANAGER_PKG_FILE $REMOTE_REPOSITORY_PATH

  echo "Upload certificates"
  LOCAL_FILE_PATH="$VOMS_CERT_FOLDER/$VOMS_CERT_FILE"
  FILE_PATH="$REMOTE_VOMS_CERT_FOLDER/$VOMS_CERT_FILE"
  mkdir_cmd="sudo mkdir -p $FILE_PATH"
  chmod_cmd="sudo chmod 777 $FILE_PATH"
  ssh_to_scheduler ${mkdir_cmd}
  ssh_to_scheduler ${chmod_cmd}
  scp_to_scheduler $LOCAL_FILE_PATH $FILE_PATH

  #KEYSTONE_LOCAL_FILE_PATH="$KEYSTONE_CERT_FOLDER/$KEYSTONE_CERT_FILE"
  #KEYSTONE_FILE_PATH="$REMOTE_KEYSTONE_CERT_FOLDER/$KEYSTONE_CERT_FILE"
  #mkdir_cmd="sudo mkdir -p $KEYSTONE_FILE_PATH"
  #chmod_cmd="sudo chmod 777 $KEYSTONE_FILE_PATH"
  #ssh_to_scheduler ${mkdir_cmd}
  #ssh_to_scheduler ${chmod_cmd}
  #scp_to_scheduler $KEYSTONE_LOCAL_FILE_PATH $KEYSTONE_FILE_PATH

  LDAP_LOCAL_PRIVATE_FILE_PATH="$LDAP_KEYS_FOLDER/$LDAP_PRIVATE_KEY"
  LDAP_LOCAL_PUBLIC_FILE_PATH="$LDAP_KEYS_FOLDER/$LDAP_PUBLIC_KEY"
  LDAP_PRIVATE_FILE_PATH="$REMOTE_LDAP_KEYS_FOLDER/$LDAP_PRIVATE_KEY"
  LDAP_PUBLIC_FILE_PATH="$REMOTE_LDAP_KEYS_FOLDER/$LDAP_PUBLIC_KEY"
  scp_to_scheduler $LDAP_LOCAL_PRIVATE_FILE_PATH $LDAP_PRIVATE_FILE_PATH
  scp_to_scheduler $LDAP_LOCAL_PUBLIC_FILE_PATH $LDAP_PUBLIC_FILE_PATH

  echo "Preparing log4j dir"
  mkdir_log4j_cmd="sudo mkdir -p /var/log/sebal-execution"
  touch_log4j_cmd="sudo touch /var/log/sebal-execution/sebal-execution.log"
  chmod_log4j_cmd="sudo chmod 777 /var/log/sebal-execution/sebal-execution.log"
  ssh_to_scheduler ${mkdir_log4j_cmd}
  ssh_to_scheduler ${touch_log4j_cmd}
  ssh_to_scheduler ${chmod_log4j_cmd}

  #Puting hostname into /etc/hosts
  insert_hostname_cmd="sudo sh $REMOTE_FILE_PATH/$SCRIPTS_DIR/insert_hostname.sh"
  ssh_to_scheduler ${insert_hostname_cmd}

  #Putting informations on Scheduler execution info.
  sed -i "/SCHEDULER_INSTANCE_ID=/ s/=.*/=$INSTANCE_ID/" $SCHEDULER_EXECUTION_INFO
  sed -i "/SCHEDULER_USER_NAME=/ s/=.*/=$USER_NAME/" $SCHEDULER_EXECUTION_INFO
  sed -i "/SCHEDULER_INSTANCE_IP=/ s/=.*/=$INSTANCE_IP/" $SCHEDULER_EXECUTION_INFO
  sed -i "/SCHEDULER_INSTANCE_PORT=/ s/=.*/=$INSTANCE_PORT/" $SCHEDULER_EXECUTION_INFO
  sed -i "/SCHEDULER_EXTRA_PORT=/ s/=.*/=$EXTRA_PORT/" $SCHEDULER_EXECUTION_INFO
  #Update DB INFO FILE with the new attachment id.
  sed -i "/DB_STORAGE_ATTACHMENT_ID=/ s/=.*/=$DB_STORAGE_ATTACHMENT_ID/" $SCHEDULER_EXECUTION_INFO
  sed -i "/DB_STORAGE_ID=/ s/=.*/=$DB_STORAGE_ID/" $SCHEDULER_EXECUTION_INFO
  sed -i "/DB_STORAGE_PORT=/ s/=.*/=$DB_STORAGE_PORT/" $SCHEDULER_EXECUTION_INFO
  sed -i "/DB_STORAGE_FORMATED=/ s/=.*/=YES/" $SCHEDULER_EXECUTION_INFO
  sed -i "/DB_STORAGE_CREATED=/ s/=.*/=YES/" $SCHEDULER_EXECUTION_INFO
  sed -i "/SCHEDULER_BASE_DIR=/ s/=.*/=/$SCHEDULER_BASE_DIR/" $SCHEDULER_EXECUTION_INFO
  sed -i "/SCHEDULER_RESTLET_PORT=/ s/=.*/=/$RESTLET_PORT/" $SCHEDULER_EXECUTION_INFO

  #echo "Executing scheduler app in VM"
  #execute_scheduler_app

  #echo "Starting restlet application"
  #execute_restlet_app $INSTANCE_IP $RESTLET_PORT
}

#do deploy
main
