#!/bin/bash
#
# Deploy the scheduler component

#FIXME add classpath and class names to constants

if [[ $# -ne 2 ]]; then
  echo "Usage:" $0 "path/to/private_key storage_size"
  exit 1
fi

PRIVATE_KEY_FILE=$1
STORAGE_SIZE=$2

if [[ ! -f "${PRIVATE_KEY_FILE}" ]]; then
  echo $PRIVATE_KEY_FILE "is not a regular file or does not exist"
  exit 1
fi

if [[ ! "${STORAGE_SIZE}" =~ ^[0-9]+$ ]]; then
  echo "Invalid storage_size" $STORAGE_SIZE
  exit 1
fi

#FIXME should not use target/classe
LOG4J=target/classe/log4j.properties
if [ -f $LOG4J ]; then
CONF_LOG=-Dlog4j.configuration=file:$LOG4J
else
CONF_LOG=
fi

#FIXME not sure if we should keep these declarations here or to load from a config file
#GLOBAL CONSTANTS
APP_FILE=sebal-scheduler-project.tar.gz
APP_FILE_LOCAL_DIR=baseapp
REMOTE_BASE_DIR=tmp
SANDBOX_DIR=sebal-scheduler
VOMS_CERT_FOLDER=tmp
VOMS_CERT_FILE=x509up_u1210
REMOTE_VOMS_CERT_FOLDER=/home/fogbow/Dev/keys/cert/

#Execution INFO
SCHEDULER_EXECUTION_INFO=scheduler-info/scheduler-exec.info
if [ ! -e "$SCHEDULER_EXECUTION_INFO" ]; then
	echo "Creating execution info file"
	touch $SCHEDULER_EXECUTION_INFO
	echo "SCHEDULER_INSTANCE_ID=" >> $SCHEDULER_EXECUTION_INFO
	echo "SCHEDULER_USER_NAME=" >> $SCHEDULER_EXECUTION_INFO
	echo "SCHEDULER_INSTANCE_IP=" >> $SCHEDULER_EXECUTION_INFO
	echo "SCHEDULER_INSTANCE_PORT=" >> $SCHEDULER_EXECUTION_INFO
	echo "SCHEDULER_EXTRA_PORT=" >> $SCHEDULER_EXECUTION_INFO
	echo "DB_STORAGE_ID=" >> $SCHEDULER_EXECUTION_INFO
	echo "DB_STORAGE_ATTACHMENT_ID=" >> $SCHEDULER_EXECUTION_INFO
	echo "DB_STORAGE_PORT=" >> $SCHEDULER_EXECUTION_INFO
	echo "DB_STORAGE_FORMATED=NO" >> $SCHEDULER_EXECUTION_INFO
	echo "DB_STORAGE_CREATED=NO" >> $SCHEDULER_EXECUTION_INFO
	echo "SCHEDULER_BASE_DIR=" >> $SCHEDULER_EXECUTION_INFO
fi
sed -i "/START_INFRASTRUCTURE_DATE=/ s/=.*/=$(date)/" $SCHEDULER_EXECUTION_INFO

source $SCHEDULER_EXECUTION_INFO

#FIXME add some doc. i did not understand the purpose of below code
STORAGE_COMMAND="FORMAT";
DATABASE_COMMAND="CREATE";

if [ "$DB_STORAGE_FORMATED" = "YES" ]; then
	STORAGE_COMMAND="RETRIEVE";
fi
if [ "$DB_STORAGE_CREATED" = "YES" ]; then
	DATABASE_COMMAND="LOAD";
fi


########### SCHEDULER INFRASTRUCTURE ##############

# It wrapps the java call to the Infrastructure main
# Globals
#   CONF_LOG
# Args
#   java_args
# Returns
function infra_call() {
  local java_args=$1
  cmd_out="$(java $CONF_LOG -cp target/sebal-scheduler-0.0.1-SNAPSHOT.jar:target/lib/* org.fogbowcloud.infrastructure.InfrastructureMain compute $CONFIG_FILE $SPEC_FILE 2>&1)"
  echo $cmd_out
}

#FIXME remove vars from inside the function. should be global
#FIXME improve contains test

# It starts scheduler VM
# Globals
#   CONFIG_FILE
#   SPEC_FILE
# Returns
#   infrastructure description

function create_scheduler_vm() {
  #CONFIG_FILE=target/classes/sebal.conf
  #SPEC_FILE=target/classes/schedulerSpec

  create_arsg="compute $CONFIG_FILE $SPEC_FILE"
  VM_SCHEDULER_INFO=`infra_call ${create_args}`

  if [[ ! $VM_SCHEDULER_INFO == *"INSTANCE_ID"* ]]; then
    echo $VM_SCHEDULER_INFO
    echo "There is no resource available for deploy Scheduler App." >&2
    exit 1
  fi

  echo $VM_SCHEDULER_INFO
}

#PREPARING VARIABLES FOR SSH/SCP
#Sample return USER_NAME=fogbow;SSH_HOST=192.168.0.1;SSH_HOST=9000;SSH_HOST=
INSTANCE_ID=$(echo $VM_SCHEDULER_INFO | cut -d";" -f1 | cut -d"=" -f2)
USER_NAME=$(echo $VM_SCHEDULER_INFO | cut -d";" -f2 | cut -d"=" -f2)
INSTANCE_IP=$(echo $VM_SCHEDULER_INFO | cut -d";" -f3 | cut -d"=" -f2)
INSTANCE_PORT=$(echo $VM_SCHEDULER_INFO | cut -d";" -f4 | cut -d"=" -f2)
EXTRA_PORT=$(echo $VM_SCHEDULER_INFO | cut -d";" -f5 | cut -d"=" -f2)

echo $INSTANCE_ID;
echo $USER_NAME;
echo $INSTANCE_IP;
echo $INSTANCE_PORT;
echo $EXTRA_PORT;

#FIXME improve function. we need return values
# It Verifies if storage info exists.
# Globals
#   DB_STORAGE_ID
#   CONFIG_FILE
#   SPEC_FILE
# Args
#  DB_STORAGE_ID

function storage_exists() {
  if [ -n "$DB_STORAGE_ID" ]; then
    check_exits_args="test-storage $DB_STORAGE_ID $CONFIG_FILE $SPEC_FILE";
    STORAGE_STATUS=`infra_call $check_exits_args`
    STORAGE_STATUS=$(echo $STORAGE_STATUS | cut -d";" -f1 | cut -d"=" -f2)
    echo "Storage status: $STORAGE_STATUS";
    if [ ! $STORAGE_STATUS = "active" ]; then
      DB_STORAGE_ID="";
    fi
  fi
}

# It creates a volume
# Globals
# Args
# Returns
function create_volume() {
  #FIXME check args
  STORAGE_COMMAND="FORMAT";
  sed -i "/DB_STORAGE_FORMATED=/ s/=.*/=NO/" $SCHEDULER_EXECUTION_INFO

  #This tow variables indicates if a new storage is been used. For new storage, the disk must be formated and the database must be created.
  create_vol_args="storage $STORAGE_SIZE $CONFIG_FILE $SPEC_FILE"
  STORAGE_INFO=`infra_call $create_vol_args`
  echo $STORAGE_INFO

  DB_STORAGE_ID=$(echo $STORAGE_INFO | cut -d";" -f1 | cut -d"=" -f2)

  echo "New storage created: "$DB_STORAGE_ID
}

# it attaches the volume to the VM
# Globals
# Args
# Returns
function attach_volume() {
#FIXME check vars
#FIXME add proper return
  echo "Attaching $DB_STORAGE_ID to $INSTANCE_ID"
  attach_arg="attachment $INSTANCE_ID $DB_STORAGE_ID $CONFIG_FILE $SPEC_FILE"
  DB_STORAGE_ATTACHMENT_INFO=`infra_call $attach_args`

  if [[ ! $DB_STORAGE_ATTACHMENT_INFO == *"ATTACHMENT_ID"* ]]; then
    echo $DB_STORAGE_ATTACHMENT_INFO
    echo "Error while attaching $DB_STORAGE_ID to $INSTANCE_ID."
    exit
  fi

  echo $DB_STORAGE_ATTACHMENT_INFO;
  DB_STORAGE_ATTACHMENT_ID=$(echo $DB_STORAGE_ATTACHMENT_INFO | cut -d";" -f1 | cut -d"=" -f2)
  echo "Attach ID: $DB_STORAGE_ATTACHMENT_ID"
  #Update Storage INFO FILE with the new attachment id.
  sed -i "/DB_STORAGE_ATTACHMENT_ID=/ s/=.*/=$DB_STORAGE_ATTACHMENT_ID/" $SCHEDULER_EXECUTION_INFO
}

#FIXME extract to a method
#Coping scripts to mount disk.
LOCAL_FILE_PATH="sebal_scripts"
REMOTE_FILE_PATH="$REMOTE_BASE_DIR";

#SSH to scheduler VM
# Globals
#   INSTANCE_PORT
#   PRIVATE_KEY_FILE
#   USER_NAME
#   INSTANCE_IP
# Args
#   remote_command
# Returns
function ssh_to_scheduler() {
  #FIXME check remote_command?
  local remote_command=$1
  ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p $INSTANCE_PORT -i $PRIVATE_KEY_FILE  $USER_NAME@$INSTANCE_IP $remote_command
}

# Globals
#   INSTANCE_PORT
#   PRIVATE_KEY_FILE
#   USER_NAME
#   INSTANCE_IP
# Args
#   src_path
#   dst_path
# Returns
function scp_to_scheduler() {
  #FIXME how about the -r modified?
  local src_path=$1
  local dst_path=$2
  scp -r -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -P $INSTANCE_PORT -i $PRIVATE_KEY_FILE $src_path $USER_NAME@$INSTANCE_IP:/$dst_path
}

# Globals
#   EXTRA_PORT
# Args
# Returns
#  postgres_port
function parse_postgres_port() {
  IFS=',' read -r -a extraPortsArray <<< $EXTRA_PORT
  arrayLength=${#extraPortsArray[@]};
  for (( i=0; i<${arrayLength}; i++ ));
  do
    actualPort=${extraPortsArray[$i]};
    if [[ $actualPort == *"postgres"* ]]; then
      postgres_port=`$actualPort | cut -d":" -f3 | tr -d`
      echo $postgres_port
    fi
  done
}

function main() {
  echo "Uploading scripts"
  scp_to_scheduler $LOCAL_FILE_PATH/ $REMOVE_FILE_PATH

  echo "Change script dir permission"
  chmod_cmd="sudo chmod -R 777 /$REMOTE_FILE_PATH/$LOCAL_FILE_PATH"
  ssh_to_scheduler $chmod_cmd

  echo "Mounting volume"
  mount_cmd="sudo sh /$REMOTE_FILE_PATH/$LOCAL_FILE_PATH/mount_partition.sh $STORAGE_COMMAND"
  ssh_to_scheduler $cmd_cmd
  sed -i "/DB_STORAGE_FORMATED=/ s/=.*/=YES/" $SCHEDULER_EXECUTION_INFO

  echo "Preparing database"
  prepdb_cmd="sudo sh /$REMOTE_FILE_PATH/$LOCAL_FILE_PATH/install_postgres.sh $DATABASE_COMMAND"
  ssh_to_scheduler $prepdb_cmd

  #do we need it here?
  echo "Installing git"
  install_git_cmd="sudo sh /$REMOTE_FILE_PATH/$LOCAL_FILE_PATH/install_git.sh"
  ssh_to_scheduler $install_git_cmd

  echo "Upload scheduler package"
  #scp_to_scheduler $APP_FILE_LOCAL_DIR/$APP_FILE $APP_FILE
  pkg_cmd="sudo sh /$REMOTE_FILE_PATH/$LOCAL_FILE_PATH/pack_blowout_repository.sh"
  ssh_to_scheduler $pkg_cmd

  #echo "Extracting SEBAL-engine"
  #extract_cmd="tar -vzxf $REMOTE_FILE_PATH"
  #ssh_to_scheduler $extract_cmd

  echo "Upload certificates"
  LOCAL_FILE_PATH="/$VOMS_CERT_FOLDER/$VOMS_CERT_FILE"
  FILE_PATH="/$REMOTE_VOMS_CERT_FOLDER/$VOMS_CERT_FILE"
  scp_to_scheduler $LOCAL_FILE_PATH $FILE_PATH

  #FIXME dst dir of private key?
  echo "Upload private key"
  #scp_to_scheduler $PRIVATE_KEY $REMOTE_FILE_PATH

  DB_STORAGE_PORT=`parse_postgres_port`

  #Putting informations on Scheduler execution info.
  sed -i "/SCHEDULER_INSTANCE_ID=/ s/=.*/=$INSTANCE_ID/" $SCHEDULER_EXECUTION_INFO
  sed -i "/SCHEDULER_USER_NAME=/ s/=.*/=$USER_NAME/" $SCHEDULER_EXECUTION_INFO
  sed -i "/SCHEDULER_INSTANCE_IP=/ s/=.*/=$INSTANCE_IP/" $SCHEDULER_EXECUTION_INFO
  sed -i "/SCHEDULER_INSTANCE_PORT=/ s/=.*/=$INSTANCE_PORT/" $SCHEDULER_EXECUTION_INFO
  sed -i "/SCHEDULER_EXTRA_PORT=/ s/=.*/=$EXTRA_PORT/" $SCHEDULER_EXECUTION_INFO
  sed -i "/DB_STORAGE_PORT=/ s/=.*/=$DB_STORAGE_PORT/" $SCHEDULER_EXECUTION_INFO
  #Update  DB INFO FILE with the new attachment id.
  sed -i "/DB_STORAGE_ATTACHMENT_ID=/ s/=.*/=$DB_STORAGE_ATTACHMENT_ID/" $SCHEDULER_EXECUTION_INFO
  sed -i "/DB_STORAGE_ID=/ s/=.*/=$DB_STORAGE_ID/" $SCHEDULER_EXECUTION_INFO
  sed -i "/DB_STORAGE_PORT=/ s/=.*/=$DB_STORAGE_PORT/" $SCHEDULER_EXECUTION_INFO
  sed -i "/DB_STORAGE_FORMATED=/ s/=.*/=YES/" $SCHEDULER_EXECUTION_INFO
  sed -i "/DB_STORAGE_CREATED=/ s/=.*/=YES/" $SCHEDULER_EXECUTION_INFO
  sed -i "/SCHEDULER_BASE_DIR=/ s/=.*/=/$SCHEDULER_BASE_DIR/" $SCHEDULER_EXECUTION_INFO
}

#do deploy
main
