#!/bin/bash
# CLI of the SEBAL engine catalog

function call_catalog() {
  local args=$*
  #local java_opts="-Xmx1G -Xss1G"
  local lpath="/usr/local/lib"
  local l4path="/local/esdras/git/sebal-engine/config/log4j.properties"
  local sebal_engine_classpath="target/sebal-scheduler-0.0.1-SNAPSHOT.jar:target/lib/*"
  local sebal_engine_class="org.fogbowcloud.sebal.engine.sebal.bootstrap.DBMain"
  #FIXME remember to change this to get info in scheduler-exec.info file, not from sebal.conf
  local sebal_engine_conf="config/sebal.conf"

#  java ${java_opts}
#    -Djava.library.path=${lpath}\
#    -cp ${sebal_engine_classpath}\
#    ${sebal_engine_class}\
#    ${DB_ADDRESS} ${DB_PORT} ${DB_USER} $DB_PASSWORD}\
#    ${args} 2>&1

   sudo java -Dlog4j.configuration=file:${l4path} -Djava.library.path=${lpath} -cp ${sebal_engine_classpath} ${sebal_engine_class} ${sebal_engine_conf} ${args} 2>&1
}

#config_file=`dirname $0`/config/catalog.config
config_file=config/catalog.config

if [[ ! -f "${config_file}" ]]; then
  echo "${config_file} is not a regular file or does not exist"
  exit 1
fi

source $config_file

if [[ $# -ne 4 ]]; then
  echo "Usage:" $0 "command first_year last_year region"
  exit 1
fi

command=$1

first_year=$2
last_year=$3
region=$4

if [[ ! "${first_year}" =~ ^[0-9]+$ ]]; then
  echo "Invalid format" ${first_year}
  exit 1
fi

if [[ ! "${last_year}" =~ ^[0-9]+$ ]]; then
  echo "Invalid format" ${last_year}
  exit 1
fi

case "${command}" in
  add)
    call_catalog add "${first_year}" "${last_year}" "${region}"
    ;;
  get)
    call_catalog get "${first_year}" "${last_year}" "${region}"
    ;;
  list)
    call_catalog list "${first_year}" "${last_year}" "${region}"
  ;;
  *)
    echo "'${command}' is not command. Available commands: [add, get, list]"
    exit 1
    ;;
esac
