#!/bin/bash
# CLI of the SEBAL engine catalog

function call_catalog() {
  local args=$1
  local lpath="/usr/local/lib"
  local sebal_engine_classpath="target/sebal-scheduler-0.0.1-SNAPSHOT.jar:target/lib/*"
  local sebal_engine_class="org.fogbowcloud.sebal.bootstrap.DBBootstrapMain"

  cmd_out="$(java -Xmx1G -Xss1G\
    -Djava.library.path=${lpath}\
    -cp ${sebal_engine_classpath}\
    ${sebal_engine_class}\
    ${DB_ADDRESS} ${DB_PORT} ${DB_USER} $DB_PASSWORD}\
    ${args} 2>&1)"
  echo $cmd_out
}

config_file=`dirname $0`/catalog.config

if [[ ! -f "${config_file}" ]]; then
  echo "${config_file} is not a regular file or does not exist"
  exit 1
fi

source $config_file

if [[ $# -ne 4 ]]; then
  echo "Usage:" $0 "command first_year last_year region"
  exit 1
fi

command=$1

first_year=$2
last_year=$3
region=$4

if [[ ! "${first_year}" =~ ^[0-9]+$ ]]; then
  echo "Invalid format" ${first_year}
  exit 1
fi

if [[ ! "${last_year}" =~ ^[0-9]+$ ]]; then
  echo "Invalid format" ${last_year}
  exit 1
fi

case "${command}" in
  create)
    call_catalog "add ${first_year} ${last_year} ${regions_path} ${regions}"
    ;;
  get)
    call_catalog "get ${first_year} ${last_year} ${region}"
    ;;
  list)
    call_catalog "list ${first_year} ${last_year} ${region_file_path} ${region}"
  ;;
  *)
    echo "'${command}' is not command. Available commands: [create, get, list]"
    exit 1
    ;;
esac