#!/bin/bash
#
# Start crawler application

if [[ $# -ne 3 ]]; then
  echo "Usage:" $0 "db-instance-ip db-port federation-member"
  exit 1
fi

#RECEIVED PARAM
DB_INSTANCE_IP=$1
DB_PORT=$2
FEDERATION_MEMBER=$3

#GLOBAL CONSTANTS
SANDBOX_DIR=/home/fogbow/sebal-engine
CONF_DIR=$SANDBOX_DIR/config
CONF_FILE_PATH=$CONF_DIR/sebal.conf
LIBRARY_PATH=/usr/local/lib
LOG4J_PATH=$SANDBOX_DIR/config/log4j.properties

function main() {
  tar -xvzf manager-pkg.tar.gz
  tar -xvzf sebal-engine-pkg.tar.gz

  rm *tar.gz

  cd $SANDBOX_DIR

  echo "Starting crawler app"
  sudo java -Dlog4j.configuration=file:$LOG4J_PATH -Djava.library.path=$LIBRARY_PATH -cp target/sebal-scheduler-0.0.1-SNAPSHOT.jar:target/lib/* org.fogbowcloud.sebal.engine.sebal.crawler.CrawlerMain $CONF_FILE_PATH $DB_INSTANCE_IP $DB_PORT $FEDERATION_MEMBER &
}

main
