#!/bin/bash
#
# Start scheduler application

if [[ $# -ne 4 ]]; then
  echo "Usage:" $0 "scheduler-instance-ip db-port nfs-instance-ip nfs-port"
  exit 1
fi

#RECEIVED PARAM
SCHEDULER_INSTANCE_IP=$1
DB_PORT=$2
NFS_INSTANCE_IP=$3
NFS_PORT=$4

#GLOBAL CONSTANTS
SEBAL_ENGINE_PATH=/home/fogbow/sebal-engine
BLOWOUT_PATH=/home/fogbow/blowout
SPEC_FILE=$SEBAL_ENGINE_PATH/config/initialSpec
CONF_DIR=$SEBAL_ENGINE_PATH/config
CONF_FILE_PATH=$CONF_DIR/sebal.conf
LIBRARY_PATH=/usr/local/lib
LOG4J_PATH=$SEBAL_ENGINE_PATH/config/log4j.properties

function main() {
  tar -xvzf manager-pkg.tar.gz
  tar -xvzf blowout-pkg.tar.gz
  tar -xvzf sebal-engine-pkg.tar.gz

  rm *tar.gz

  cd $BLOWOUT_PATH/scripts

  make su_command

  cd $SEBAL_ENGINE_PATH

  echo "Starting scheduler app"
  sudo java -Dlog4j.configuration=file:$LOG4J_PATH -Djava.library.path=$LIBRARY_PATH -cp target/sebal-scheduler-0.0.1-SNAPSHOT.jar:target/lib/* org.fogbowcloud.sebal.engine.scheduler.SebalMain $CONF_FILE_PATH $SCHEDULER_INSTANCE_IP $DB_PORT $NFS_INSTANCE_IP $NFS_PORT &
}

main
