#!/bin/bash
. CLI.properties

define_parameters() {
	while [ ! -z $1 ]; do
		case $1 in
			-j | --jdffilepath)
				shift;
				jdffilepath=$1;
				;;
			-s | --schedpath)
				shift;
				schedpath=$1;
				;;
			-f | --friendly)
				shift;
				friendly=$1;
				;;
		esac
		shift
	done
}

while test $# -gt 0; do
        case "$1" in
		GET)
			shift
			if test $# -gt 0; then
				response=$(curl -G "$host/sebal-scheduler/job/$1")
				echo $response
			else 
				response=$(curl -G "$host/sebal-scheduler/job")
				echo $response
			fi
			shift
			;;
		POST)
			shift
			define_parameters $@
			if [[ $jdffilepath ]]; then
				shift
#FIXME: Encapsular o post num metodo
				if [[ $friendly ]]; then
					shift
					if [[ $schedpath ]]; then
						response=$(curl -X POST --data jdffilepath=$jdffilepath --data schedpath=$schedpath --data friendly=$friendly $host/sebal-scheduler/job)				
						echo $response
						break
					else
						response=$(curl -X POST --data jdffilepath=$jdffilepath --data friendly=$friendly $host/sebal-scheduler/job)	
						echo $response
						break								
					fi
					shift
				else
					shift
					if [[ $schedpath ]]; then
						response=$(curl -X POST --data jdffilepath=$jdffilepath --data schedpath=$schedpath $host/sebal-scheduler/job)				
						echo $response
					else
						response=$(curl -X POST --data jdffilepath=$jdffilepath $host/sebal-scheduler/job)	
						echo $response								
					fi
					shift
				fi
				shift 
			else 
				echo "There was no JDF file informed"
			fi
			shift
			;;
		STOP)
			shift
			if test $# -gt 0; then
				response=$(curl -X DELETE "$host/sebal-scheduler/job/$1")
				echo $response
			else 
				echo "No Id or friendly named was informed"
			fi
			shift
			;;

		*)
			echo "no valid function was selected, valid operations are: get, post and stop"
			break
			;;
        esac
done



