#!/bin/bash

## This script get digest (sha256 hash of a docker image) based in two informations:
## - Docker image: a file, comprised of multiple layers, used to execute code in a Docker container
## - Docker image tag: specific image version/variant
## Note: The registry host: https://hub.docker.com/v2

IMAGE=$1
TAG=$2

CURL=`which curl`
JQ=`which jq`
SED=`which sed`

REGISTRY_HOST="https://hub.docker.com/v2"
PATH="repositories/$IMAGE/tags"

DIGEST=`$CURL -f --silent --header "Accept: application/json" $REGISTRY_HOST/$PATH | $JQ ".results[] | select(.name == \"$TAG\") | .images[].digest" | $SED -e 's/\"//g'`

if [ ! $DIGEST ]
then
  exit 1
fi

if [ ${#DIGEST} -ne 71 ]
then
  exit 2
fi

echo $DIGEST
