#!/bin/bash

FTP_SERVER_USER=$1
FTP_SERVER_IP=$2
FTP_SERVER_PORT=$3
REMOTE_OUTPUT_DIR=$4
LOCAL_OUTPUT_DIR=$5

PRIVATE_KEY_PATH=/home/ubuntu/keys/fetcher_key_rsa
TEMPORARY_OUTPUT_ENDPOINT=output

echo -e "get -r $REMOTE_OUTPUT_DIR\nquit\n" | sftp -i $PRIVATE_KEY_PATH -o "StrictHostKeyChecking=no" -P $FTP_SERVER_PORT $FTP_SERVER_USER@$FTP_SERVER_IP
mv $TEMPORARY_OUTPUT_ENDPOINT/* $LOCAL_OUTPUT_DIR
rm -r $TEMPORARY_OUTPUT_ENDPOINT/
